import AppKit
import CryptoKit
import os

let log = Logger(subsystem: "dev.clipstash.ClipStash", category: "history")

struct ClipItem: Codable, Identifiable, Equatable, Hashable {
    enum Kind: String, Codable { case text, link, image, files }

    var id = UUID()
    var kind: Kind
    var text: String?
    var rtf: Data?
    var imageFile: String?
    var filePaths: [String]?
    var sourceBundleID: String?
    var sourceName: String?
    var date = Date()
    var pinned = false
    var hash: String

    /// What search matches against and what a row shows.
    var title: String {
        switch kind {
        case .text, .link: return text ?? ""
        case .image: return "Image"
        case .files: return (filePaths ?? []).map { ($0 as NSString).lastPathComponent }.joined(separator: ", ")
        }
    }

    var url: URL? { kind == .link ? text.flatMap { URL(string: $0.trimmingCharacters(in: .whitespacesAndNewlines)) } : nil }
}

struct ClipSource: Identifiable, Hashable {
    let bundleID: String
    let name: String
    let count: Int
    var id: String { bundleID }
}

/// Watches the general pasteboard and keeps a persistent, de-duplicated history.
@MainActor
final class HistoryStore: ObservableObject {
    static let shared = HistoryStore()

    @Published private(set) var items: [ClipItem] = []
    @Published var isPaused = false {
        // Resuming by hand also ends safe mode.
        didSet { if !isPaused && inSafeMode { leaveSafeMode() } }
    }
    /// Safe mode after repeated crashes: capturing starts paused (a clipboard item is the likeliest
    /// thing to crash at every launch) until it's resumed.
    @Published private(set) var inSafeMode = Stability.safeMode
    /// "ClipStash quit unexpectedly and was reopened", until dismissed.
    @Published var crashNotice = Stability.safeMode ? nil : Stability.previousCrash?.message
    /// A persistent problem worth showing in the UI (save failures, a recovered corrupt file).
    @Published var problem: String?

    private let maxTextBytes = 5_000_000
    private let maxImageBytes = 25_000_000

    let imagesDir: URL
    private let indexURL: URL
    private var lastChangeCount: Int
    private var timer: Timer?
    private var pendingSave: DispatchWorkItem?
    /// Saves run one at a time, in order, so an older snapshot can never overwrite a newer one.
    private let saveQueue = DispatchQueue(label: "dev.clipstash.save", qos: .utility)
    private let imageQueue = DispatchQueue(label: "dev.clipstash.images", qos: .userInitiated)

    /// Markers apps like password managers put on secrets they copy (see nspasteboard.org).
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    private init() {
        let support = (FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent("Library/Application Support"))
            .appendingPathComponent("ClipStash", isDirectory: true)
        imagesDir = support.appendingPathComponent("images", isDirectory: true)
        indexURL = support.appendingPathComponent("history.json")
        try? FileManager.default.createDirectory(at: imagesDir, withIntermediateDirectories: true)

        lastChangeCount = NSPasteboard.general.changeCount
        load()
        if inSafeMode { isPaused = true }
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    func leaveSafeMode() {
        Stability.leaveSafeMode()
        inSafeMode = false
        if isPaused { isPaused = false }
    }

    /// Loads the history. An unreadable file is set aside (never overwritten) so nothing is lost.
    private func load() {
        guard FileManager.default.fileExists(atPath: indexURL.path) else { return }
        do {
            let data = try Data(contentsOf: indexURL)
            items = try JSONDecoder().decode([ClipItem].self, from: data)
            // Items saved before link detection existed are re-classified.
            for index in items.indices where items[index].kind == .text && Self.isLink(items[index].text ?? "") {
                items[index].kind = .link
            }
        } catch {
            let stamp = ISO8601DateFormatter().string(from: Date()).replacingOccurrences(of: ":", with: "-")
            let backup = indexURL.deletingLastPathComponent().appendingPathComponent("history-unreadable-\(stamp).json")
            try? FileManager.default.moveItem(at: indexURL, to: backup)
            log.error("History file unreadable, moved to \(backup.lastPathComponent, privacy: .public): \(error.localizedDescription, privacy: .public)")
            problem = "Your saved history couldn't be read, so ClipStash started a new one. The old file was kept as \(backup.lastPathComponent)."
        }
    }

    var sources: [ClipSource] {
        var counts: [String: (name: String, count: Int)] = [:]
        for item in items {
            guard let id = item.sourceBundleID else { continue }
            counts[id, default: (item.sourceName ?? id, 0)].count += 1
        }
        return counts.map { ClipSource(bundleID: $0.key, name: $0.value.name, count: $0.value.count) }
            .sorted { $0.count > $1.count }
    }

    var storageBytes: Int {
        let files = (try? FileManager.default.contentsOfDirectory(at: imagesDir, includingPropertiesForKeys: [.fileSizeKey])) ?? []
        let images = files.reduce(0) { $0 + ((try? $1.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0) }
        let index = (try? indexURL.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0
        return images + index
    }

    // MARK: Capture

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard !isPaused, let item = capture(pasteboard) else { return }
        insert(item)
    }

    private func capture(_ pasteboard: NSPasteboard) -> ClipItem? {
        let types = pasteboard.types ?? []
        if types.contains(where: { Self.ignoredTypes.contains($0.rawValue) }) { return nil }

        let source = NSWorkspace.shared.frontmostApplication
        if let id = source?.bundleIdentifier, Prefs.ignoredApps.contains(id) { return nil }

        func make(_ kind: ClipItem.Kind, hashing data: Data) -> ClipItem {
            ClipItem(kind: kind, sourceBundleID: source?.bundleIdentifier, sourceName: source?.localizedName,
                     hash: kind.rawValue + ":" + SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined())
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            var item = make(.files, hashing: Data(paths.joined(separator: "\n").utf8))
            item.filePaths = paths
            return item
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           string.utf8.count <= maxTextBytes {
            var item = make(Self.isLink(string) ? .link : .text, hashing: Data(string.utf8))
            item.text = string
            item.rtf = pasteboard.data(forType: .rtf).flatMap { $0.count <= maxTextBytes ? $0 : nil }
            return item
        }

        if let raw = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff), raw.count <= maxImageBytes {
            // Converting and hashing a large screenshot can take a while: do it off the main thread.
            let template = make(.image, hashing: Data())
            let dir = imagesDir
            imageQueue.async {
                guard let png = NSBitmapImageRep(data: raw)?.representation(using: .png, properties: [:]) else {
                    log.error("Couldn't decode copied image (\(raw.count) bytes)")
                    return
                }
                var item = template
                item.hash = "image:" + SHA256.hash(data: png).map { String(format: "%02x", $0) }.joined()
                item.imageFile = item.id.uuidString + ".png"
                let url = dir.appendingPathComponent(item.imageFile!)
                DispatchQueue.main.async {
                    let store = HistoryStore.shared
                    if !store.items.contains(where: { $0.hash == item.hash }) {
                        do {
                            try png.write(to: url, options: .atomic)
                        } catch {
                            store.report("Couldn't save a copied image", error)
                            return
                        }
                    }
                    store.insert(item)
                }
            }
        }
        return nil
    }

    private static func isLink(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed),
              let scheme = url.scheme?.lowercased() else { return false }
        return ["http", "https", "ftp", "mailto"].contains(scheme) && (url.host != nil || scheme == "mailto")
    }

    fileprivate func insert(_ item: ClipItem) {
        if let index = items.firstIndex(where: { $0.hash == item.hash }) {
            var existing = items.remove(at: index)
            existing.date = item.date
            items.insert(existing, at: 0)
        } else {
            items.insert(item, at: 0)
            trim()
        }
        scheduleSave()
    }

    func trim() {
        let limit = Prefs.historyLimit
        guard limit > 0 else { return }
        let excess = items.filter { !$0.pinned }.dropFirst(limit)
        guard !excess.isEmpty else { return }
        let ids = Set(excess.map(\.id))
        items.removeAll { ids.contains($0.id) }
        for item in excess { deleteFiles(of: item) }
        scheduleSave()
    }

    // MARK: Actions

    enum CopyOutcome: Equatable {
        case copied
        case copiedWithWarning(String)
        case failed(String)
    }

    /// Puts an item back on the pasteboard and moves it to the top of the history.
    /// Validates first, so a failure leaves whatever is on the clipboard untouched.
    @discardableResult
    func copy(_ item: ClipItem, plainText: Bool = false) -> CopyOutcome {
        let pasteboard = NSPasteboard.general
        var outcome = CopyOutcome.copied
        switch item.kind {
        case .text, .link:
            pasteboard.clearContents()
            if !plainText, let rtf = item.rtf { pasteboard.setData(rtf, forType: .rtf) }
            pasteboard.setString(item.text ?? "", forType: .string)
            if let url = item.url { pasteboard.setString(url.absoluteString, forType: .URL) }
        case .image:
            guard let url = imageURL(for: item), let data = try? Data(contentsOf: url) else {
                return .failed("This image's file is missing from ClipStash's storage.")
            }
            pasteboard.clearContents()
            pasteboard.setData(data, forType: .png)
            if let tiff = NSImage(data: data)?.tiffRepresentation { pasteboard.setData(tiff, forType: .tiff) }
        case .files:
            let paths = item.filePaths ?? []
            let existing = paths.filter { FileManager.default.fileExists(atPath: $0) }
            guard !existing.isEmpty else {
                return .failed(paths.count == 1 ? "This file no longer exists." : "None of these files exist anymore.")
            }
            if existing.count < paths.count {
                outcome = .copiedWithWarning("\(paths.count - existing.count) of \(paths.count) files no longer exist and were skipped.")
            }
            pasteboard.clearContents()
            pasteboard.writeObjects(existing.map { URL(fileURLWithPath: $0) as NSURL })
        }
        lastChangeCount = pasteboard.changeCount // don't re-capture our own write

        if let index = items.firstIndex(where: { $0.id == item.id }) {
            var moved = items.remove(at: index)
            moved.date = Date()
            items.insert(moved, at: 0)
            scheduleSave()
        }
        return outcome
    }

    func togglePin(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        scheduleSave()
    }

    func delete(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        deleteFiles(of: item)
        scheduleSave()
    }

    func clearUnpinned() {
        let removed = items.filter { !$0.pinned }
        items.removeAll { !$0.pinned }
        for item in removed { deleteFiles(of: item) }
        scheduleSave()
    }

    func imageURL(for item: ClipItem) -> URL? {
        item.imageFile.map { imagesDir.appendingPathComponent($0) }
    }

    // MARK: Persistence

    private func deleteFiles(of item: ClipItem) {
        guard let file = item.imageFile, !items.contains(where: { $0.imageFile == file }) else { return }
        do {
            try FileManager.default.removeItem(at: imagesDir.appendingPathComponent(file))
        } catch CocoaError.fileNoSuchFile {
            // Already gone; nothing to do.
        } catch {
            log.error("Couldn't delete image \(file, privacy: .public): \(error.localizedDescription, privacy: .public)")
        }
    }

    func report(_ what: String, _ error: Error) {
        log.error("\(what, privacy: .public): \(error.localizedDescription, privacy: .public)")
        problem = "\(what): \(error.localizedDescription)"
    }

    private func scheduleSave() {
        pendingSave?.cancel()
        let snapshot = items
        let url = indexURL
        let work = DispatchWorkItem {
            do {
                try Self.write(snapshot, to: url)
                DispatchQueue.main.async {
                    let store = HistoryStore.shared
                    if store.problem?.hasPrefix("Couldn't save") == true { store.problem = nil }
                }
            } catch {
                DispatchQueue.main.async { HistoryStore.shared.report("Couldn't save clipboard history", error) }
            }
        }
        pendingSave = work
        saveQueue.asyncAfter(deadline: .now() + 1, execute: work)
    }

    /// Called at quit: waits for any in-flight save, then writes the latest state.
    func saveNow() {
        pendingSave?.cancel()
        let snapshot = items
        let url = indexURL
        saveQueue.sync {
            do { try Self.write(snapshot, to: url) } catch { log.error("Final save failed: \(error.localizedDescription, privacy: .public)") }
        }
    }

    private nonisolated static func write(_ items: [ClipItem], to url: URL) throws {
        let data = try JSONEncoder().encode(items)
        try data.write(to: url, options: .atomic)
    }
}
